# 자판 배열
Keyboard=Dubeolsik
# 자동 재배열
AutoReorder=True
# 같은 글쇠 두 번 입력 시 결합
CombiOnDoubleStroke=False
# 초성이 아닌 자모 결합
NonChoseongCombi=True
# 단어 단위 확정
WordCommit=False
# 한자 모드
HanjaMode=False

[HanjaModeToggleKey]
0=Hangul_Hanja
1=F9

[PrevPage]
0=Up

[NextPage]
0=Down

[PrevCandidate]
0=Shift+Tab

[NextCandidate]
0=Tab

